//
//  WelcomeView.swift
//  JapaneseGallery
//
//  Created by 杉山栞奈 on 5/9/25.
//

import SwiftUI

struct WelcomeView: View {
    @State private var isActive = false

    var body: some View {
        if isActive {
            ContentView()
        } else {
            ZStack {
                // Background image
                Image("gallery")
                    .resizable()
                    .scaledToFill()
                    .ignoresSafeArea()

                // Semi-transparent overlay to darken the image
                Color.black.opacity(0.4)
                    .ignoresSafeArea()

                // Foreground content
                VStack(spacing: 20) {
                    Text("Welcome to Japanese Picture Gallery")
                        .font(.title)
                        .fontWeight(.bold)
                        .multilineTextAlignment(.center)
                        .foregroundColor(.white)

                    Text("""
                    These pictures were taken by the builder of this app, a Japanese woman who was born and raised in Japan. I like taking pictures and I wanted to share the beautiful scenery of Japan. Please enjoy these pictures.
                    """)
                        .font(.body)
                        .foregroundColor(.white)
                        .multilineTextAlignment(.center)
                        .padding(.horizontal)

                    Text("※ Some pictures were generated by AI to help support the images of each prefecture.")
                        .font(.footnote)
                        .foregroundColor(.white.opacity(0.8))
                        .multilineTextAlignment(.center)
                        .padding(.top, 10)

                    Button(action: {
                        withAnimation {
                            isActive = true
                        }
                    }) {
                        Text("Enter the Gallery")
                            .font(.headline)
                            .foregroundColor(.white)
                            .padding()
                            .frame(maxWidth: .infinity)
                            .background(Color.blue)
                            .cornerRadius(12)
                            .padding(.horizontal)
                    }
                    .padding(.top, 30)
                }
                .padding()
            }
        }
    }
}
